export const TILE_WIDTH_PX = 100;
export const TILE_HEIGHT_PX = 57.735; // this is mathematically derived by hand based on the image asset
export const TILE_SIDE_LENGTH_PX = Math.sqrt(Math.pow(TILE_WIDTH_PX/2, 2) + Math.pow(TILE_HEIGHT_PX/2, 2));
export const TILE_TOP_SURFACE_HEIGHT_PX = 38.42;
export const TILE_Z_HEIGHT_PX = 20.69;
export const TILE_ISO_WIDTH_PX = 51;
export const BOARD_WIDTH_TILES = 40;
export const BOARD_HEIGHT_TILES = 30;
export const VISIBLE_WIDTH_TILES = 4;
export const VISIBLE_HEIGHT_TILES = 8;
export const MOVEMENT_SPEED_FACTOR = 7;
